### ISSUE TITLE
Additional reference and suggestion for a new subsection

### ISSUE THREAD

**Issue by fabioricciato** [AndrewZhou924/Awesome-model-inversion-attack#2]
This site is a very useful resource! If you allow me a suggestion to improve it even further, I would invite you to consider creating a new subsection, whose title could be "Attacks against synthetic data". You could move there the entry 
"2023 - arXiv A Linear Reconstruction Approach for Attribute Inference Attacks against Synthetic Data", 
that is currently under "Other", 
and add also this important paper from USENIX 2022 
"Synthetic Data – Anonymisation Groundhog Day" - https://www.usenix.org/system/files/sec22summer_stadler.pdf

I think that inferring (membership or attributes)  "from the model" is very tightly connected to inferring  "from the data generated  by the model", and it would be good fo the community to find the latter research area clearly identified on this site. 

Just a suggestion -- thanks again for setting up this awesome list!

**Comment by AndrewZhou924** [comment]
Thanks for your constructive suggestion! We will take your suggestion and upgrade this awesome list in the coming days.

**Comment by XuanLi728** [comment]
Updated. Thanks for the suggestion!
